services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: api_id_here
      TELEGRAM_API_HASH: api_hash_here
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
    network_mode: host
  
  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    
    ports:
      - "4416:4416"
    network_mode: host

  bot:
    image: noiceytdbot
    build: ./
    depends_on:
      - telegram-bot-api
      - pot-provider
    environment:
      BOT_TOKEN: bot_token_here
    volumes:
      - ./bot:/usr/src/app/bot
    network_mode: host

volumes:
  telegram-bot-api-data: